#desenhando o tabuleiro do projeto
#cada elemento da lista a baixo é feito para representar um membro sendo riscado a cada erro
board = [
    "<"*10+"VAMOS COMEÇAR"+10*">",
    ' ______\n'
    ' |     |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '_______|',
    ' ______\n'
    ' |     |\n'
    ' 0     |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '_______|',
    ' ______\n'
    ' |     |\n'
    ' 0     |\n'
    '/      |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '_______|',
    ' ______\n'
    ' |     |\n'
    ' 0     |\n'
    '/|     |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '_______|',
    ' ______\n'
    ' |     |\n'
    ' 0     |\n'
    '/|\\   |\n'
    '       |\n'
    '       |\n'
    '       |\n'
    '_______|',
    ' ______\n'
    ' |     |\n'
    ' 0     |\n'
    '/|\\    |\n'
    '/      |\n'
    '       |\n'
    '       |\n'
    '_______|',
    ' ______\n'
    ' |     |\n'
    ' 0     |\n'
    '/|\\    |\n'
    '/ \\    |\n'
    '       |\n'
    '       |\n'
    '_______|'
]
